const CleanWebpackPlugin = require("clean-webpack-plugin");
const path = require("path");
const webpack = require("webpack");
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

const BUILD_DIR = path.resolve(__dirname, "lib");
const APP_DIR = path.resolve(__dirname, "src");

module.exports = {
  entry: ["index.tsx"],
  resolve: {
    modules: [APP_DIR, "node_modules"],
    extensions: [".js", ".jsx", ".ts", ".tsx"]
  },
  output: {
    path: BUILD_DIR,
    publicPath: "/",
    filename: "[hash].[name].js",
    chunkFilename: "[chunkhash].chunk.js"
  },
  module: {
    rules: [
      {
        enforce: "pre",
        test: /\.scss$/,
        include: APP_DIR,
        use: [
          "style-loader",
          {
            loader: "typings-for-css-modules-loader",
            options: {
              modules: true,
              namedExport: true,
              camelCase: true,
              localIdentName: "[name]__[local]--[hash:base64:8]",
              banner:
                "// This file is automatically generated by typings-for-css-modules.\n// Please do not change this file!\n"
            }
          },
          "sass-loader"
        ]
      },
      {
        test: /\.tsx?$/,
        include: APP_DIR,
        loaders: [
          { loader: "babel-loader" },
          { loader: "ts-loader", options: { transpileOnly: true } }
        ]
      },
      {
        test: /\.(png|jpe?g|gif|ico|svg)(\?\S*)?$/,
        include: APP_DIR,
        use: [
          {
            loader: "file-loader"
          }
        ]
      }
    ]
  },
  plugins: [
    new CleanWebpackPlugin(["lib"], { verbose: false }),
    new HtmlWebpackPlugin({
      template: "./index.ejs"
    }),
    new ForkTsCheckerWebpackPlugin(),
    new webpack.WatchIgnorePlugin([/css\.d\.ts$/, /scss\.d\.ts$/])
  ]
};
