// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!

export const message: string;
export const message__italic: string;
export const messageItalic: string;
